spring:
  freemarker:
    checkTemplateLocation: false

  jpa:
    database: mysql
    show-sql: true
    hibernate.ddl-auto: create-drop

  datasource:
    database: mysql
    url: jdbc:mysql://localhost/interview_hq
    username: boot_u
    password: b00t!ful

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR

server:
  port: 8080

security:
  user:
    password: password
