application:
  name: "Interview HQ"
  code: interview_hq

spring:
  main:
    show-banner: false

  thymeleaf:
    enabled: true
    #Support hot deployment of thymeleaf templates
    cache: false

  jpa:
    database: mysql
    show-sql: true
    hibernate.ddl-auto: create-drop

  datasource:
    name: interview_hq
    database: mysql
    url: jdbc:mysql://localhost/interview_hq
    username: boot_u
    password: b00t!ful

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"

  data:
    rest:
      base-uri: /data/rest/v1/

logging:
  file: ${application.code}.log

  level:
    org.springframework.web: INFO
    org.hibernate: ERROR

server:
  port: 8080

security:
  user:
    password: password
